# For the full spec setting and usage, see ./pkg/apis/frameworkcontroller/v1/types.go
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: service
spec:
  executionType: Start
  retryPolicy:
    fancyRetryPolicy: false
    maxRetryCount: -2
  taskRoles:
  - name: server
    taskNumber: 1
    frameworkAttemptCompletionPolicy:
      minFailedTaskCount: 1
      minSucceededTaskCount: -1
    task:
      retryPolicy:
        fancyRetryPolicy: false
        maxRetryCount: -2
      pod:
        #metadata:
        #  labels:
        #    app: server
        spec:
          restartPolicy: Always
          containers:
          - name: nginx
            image: nginx:stable
            ports:
            - containerPort: 80
---
# Post to {kubeApiServerAddress}/api/v1/namespaces/default/services/
# Then the above nginx server can be accessed by http://10.169.8.232:30170
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    # Using predefined labels
    FC_FRAMEWORK_NAME: service
    FC_TASKROLE_NAME: server
    # Also can use customized labels
    #app: server
  type: NodePort
  ports:
  - targetPort: 80
    port: 30170
    nodePort: 30170
